DROP TABLE IF EXISTS "SequelizeMeta" CASCADE;
DROP TABLE IF EXISTS "Users" CASCADE;
DROP TABLE IF EXISTS "Categories" CASCADE;
DROP TABLE IF EXISTS "Incomes" CASCADE;
DROP TABLE IF EXISTS "Achievements" CASCADE;
DROP TABLE IF EXISTS "Budgets" CASCADE;
DROP TYPE IF EXISTS "enum_Categories_type" CASCADE; 